#!/bin/bash
# set -x
SSHMATE_FILE="./.sshmate"
DELIMITER="|"

flag_add_name=false
flag_add_connection=false

cecho()
{
  CLEAR="\033[2J"
  BLACK="\033[30m"
  RED="\033[31m"
  GREEN="\033[32m"
  YELLOW="\033[33m"
  WHITE="\033[99m"
  ENDCOLOR="\033[0m"
  while [ "$1" ]; do
    case $1 in
         -y|--yellow) color=$YELLOW;;
         -r|--red) color=$RED;;
         -g|--green) color=$GREEN;;
         -b|--black) color=$BLACK;;
         -w|--white) color=$WHITE;;
         -c|--clear) color=$CLEAR;;
         *) echo -en "$1"; shift; continue;;
    esac
    echo -ne "${color}"
    shift
  done
  echo -ne "${ENDCOLOR}"
}

add_connection()
{
  cecho --yellow "Adding [$2] connection with the name: $1"
  echo "$1|$2" >> $SSHMATE_FILE
}

check_connection_in_file()
{
  grep -w $1 $SSHMATE_FILE
  return $?
}

get_connection_by_name()
{
    connection=$(grep -w -i $1 $SSHMATE_FILE)
    echo $connection
}

get_connection_cmd()
{
    read connection<<<$(echo $1 | cut -d "$DELIMITER" -f 2)
    echo $connection
}

split_connection_entry()
{
    while IFS= read -r line
    do
        read name<<<$(echo $line | cut -d "$DELIMITER" -f 1)
        read connection<<<$(echo $line | cut -d "$DELIMITER" -f 2)
        printf "%-20s  ==>  %s\n" "$(cecho --red $name)" "$(cecho --green $connection)"
    done < "$SSHMATE_FILE"
}

while getopts "a:n:ld:c:" flag
do
    case "${flag}" in
        a) 
            new_connection=${OPTARG}
            flag_add_name=true
            #add_connection $new_connection
            echo "adding new connection.."
            ;;
        n)
            connection_name=${OPTARG}
            flag_add_connection=true
            #check_connection_in_file
            ;;
        l)
            #list_connection=${OPTARG}
            cecho --yellow "listing all SSH connections...\n"
            split_connection_entry
            ;;
        d)
            new_connection=${OPTARG}
            cecho --red "deleting connection: $new_connection\n"
            ;;
        c)
            check_connection=${OPTARG}
            cecho --yellow "checking connection:" --green $check_connection
            echo
            check_connection=$(check_connection_in_file $check_connection)
            connection=$(get_connection_by_name $check_connection)
            connection_cmd=$(get_connection_cmd $connection)
            cecho --yellow "connecting to: " --green $connection_cmd
            echo
            ssh $connection_cmd
            ;;
    esac
done

if $flag_add_name && $flag_add_connection; then
  add_connection "$connection_name" "$new_connection"
fi


